@exercise_state_updates_readmodel_HostAddress = http://localhost:5294

GET {{exercise_state_updates_readmodel_HostAddress}}/
Accept: application/json

###
# Should create first disconnection
POST {{exercise_state_updates_readmodel_HostAddress}}/1
Content-Type: application/json

{
    "hardwareUnitId": "i1",
    "state": "DISCONNECTED",
    "occurredAt": "2023-10-31T09:00:00.594Z"
}

###
# Should update the endTime
POST {{exercise_state_updates_readmodel_HostAddress}}/1
Content-Type: application/json

{
    "hardwareUnitId": "i1",
    "state": "CONNECTED",
    "occurredAt": "2023-10-31T10:00:00.594Z"
}

###
# Should create second disconnection
POST {{exercise_state_updates_readmodel_HostAddress}}/1
Content-Type: application/json

{
    "hardwareUnitId": "i1",
    "state": "DISCONNECTED",
    "occurredAt": "2023-10-31T11:00:00.594Z"
}

###
# Should update endtime of second disconnection
# and create third disconnection
POST {{exercise_state_updates_readmodel_HostAddress}}/1
Content-Type: application/json

{
    "hardwareUnitId": "i1",
    "state": "WAITING",
    "occurredAt": "2023-10-31T12:00:00.594Z"
}